apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatekeeper-system
helmCharts:
- name: gatekeeper
  releaseName: gatekeeper
  includeCRDs: false
  version: v3.9.1
  namespace: gatekeeper-system
  repo: https://open-policy-agent.github.io/gatekeeper/charts